# Generated by Django 5.0 on 2023-12-24 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
        ('shop', '0007_alter_product_related_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='shop.product'),
        ),
    ]
