# Generated by Django 5.0.7 on 2025-07-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='شماره سفارش'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
