# Generated by Django 5.0 on 2023-12-24 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='related_products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.product'),
        ),
    ]
