# Generated by Django 5.0 on 2023-12-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_related_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='color',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
