# Generated by Django 5.0.7 on 2025-07-24 22:13

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_inventorylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
