# Generated by Django 5.0.7 on 2025-07-24 22:35

import imagekit.models.fields
import products.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=products.models.get_product_upload_path),
        ),
    ]
